name: Deploy to Github Pages
on:
  push:
    branches: [ main ]

jobs:
  gh_pages_deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
          with:
            node-version: '12'

      - name: Set Creds
          run: git config user.name "CorbynG98" && git config user.email "corbyn.greenwood.98@gmail.com"

      - name: npm ci, deploy (custom script)
        run: |
          npm ci
          npm run deploy --if-present